### ISSUE TITLE
Enabling application

### ISSUE THREAD

**Issue by erikcek** [grafana/grafana-starter-app#23]
HI,

I have a problem with activating this plugin. I can build, the plugin but after I navigate to custom routes I get the error message "Application Not Enabled". 

I can't figure out how to enable the plugin. (I can't see the enable button in the list of all plugins)

Can someone help me with it?
Thanks.

**Comment by wbrowne** [comment]
Hi @erikcek, have you tried going to the route `/plugins/myorgid-simple-app/` or clicking the plugin from the plugins list page? See
![image](https://user-images.githubusercontent.com/1173299/110828813-b8fa0e00-8297-11eb-99b1-925e327fb4bd.png)

From there you should be able to enable the plugin:
![image](https://user-images.githubusercontent.com/1173299/110828961-e646bc00-8297-11eb-8d96-7c64a10b08d2.png)

Let me know if that works 😄

**Comment by erikcek** [comment]
Thank you @wbrowne for the quick response :)

well, I tied but unfortunately, I can't locate the enable button. 

![grafana](https://user-images.githubusercontent.com/32076170/110924197-0e7afd00-8322-11eb-8873-4b4c69233a18.PNG)

This is what I can see in route /plugins/myorgid-simple-app/.

**Comment by wbrowne** [comment]
Ah looks like there was a previous issue with this https://github.com/grafana/grafana-starter-app/pull/22. If you update to master and re-build, then hopefully you get what you expect.

**Comment by erikcek** [comment]
Thank you very much @wbrowne  :) it works now.
